version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      time: "12:00"
      timezone: America/New_York
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    groups:
      ruby-bundler:
        patterns:
          - "*"
